# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Augmented Campus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Augmented Campus
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'Augmented CampusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
